spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/teams
    username: root
    password: 123
  sql:
    init:
      platform: postgres
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: validate
